import { z } from "zod";

export const TIPOS_DO_ITEM_COMERCIAL = ["modulo", "usuario", "servico"] as const;

export const itemDoCatalogoSchema = z.object({
  id: z.string().uuid().optional(),
  codigo: z
    .string()
    .trim()
    .regex(/^[a-z0-9_]+$/)
    .max(80),
  nome: z.string().trim().min(2).max(160),
  descricao: z.string().trim().max(500).default(""),
  categoria: z.enum(TIPOS_DO_ITEM_COMERCIAL),
  cobranca: z.enum(["mensal", "unica"]).default("mensal"),
  preco_escritorio_cents: z.number().int().min(0),
  preco_departamento_cents: z.number().int().min(0),
  setup_cents: z.number().int().min(0).default(0),
  ativo: z.boolean().default(true),
  ordem: z.number().int().min(0).max(10_000).default(0),
});

export const catalogoComercialSchema = z.object({ itens: z.array(itemDoCatalogoSchema).max(200) });
export type ItemDoCatalogo = z.infer<typeof itemDoCatalogoSchema>;

export const CATALOGO_COMERCIAL_INICIAL: ItemDoCatalogo[] = [
  {
    codigo: "gestao_processos",
    nome: "Gestão de processos",
    descricao: "Organiza processos, prazos, movimentações e alertas.",
    categoria: "modulo",
    cobranca: "mensal",
    preco_escritorio_cents: 14225,
    preco_departamento_cents: 14225,
    setup_cents: 0,
    ativo: true,
    ordem: 10,
  },
  {
    codigo: "publicacoes",
    nome: "Publicações",
    descricao: "Captura e organiza publicações para a equipe jurídica.",
    categoria: "modulo",
    cobranca: "mensal",
    preco_escritorio_cents: 14225,
    preco_departamento_cents: 14225,
    setup_cents: 0,
    ativo: true,
    ordem: 20,
  },
  {
    codigo: "contratos",
    nome: "Contratos",
    descricao: "Centraliza contratos, vencimentos, responsáveis e documentos.",
    categoria: "modulo",
    cobranca: "mensal",
    preco_escritorio_cents: 12800,
    preco_departamento_cents: 12800,
    setup_cents: 0,
    ativo: true,
    ordem: 30,
  },
  {
    codigo: "atividades_juridicas",
    nome: "Atividades jurídicas",
    descricao: "Distribui tarefas e acompanha a execução da rotina jurídica.",
    categoria: "modulo",
    cobranca: "mensal",
    preco_escritorio_cents: 0,
    preco_departamento_cents: 0,
    setup_cents: 0,
    ativo: true,
    ordem: 40,
  },
  {
    codigo: "assinatura_digital",
    nome: "Assinatura digital",
    descricao: "Fluxos de assinatura integrados à operação.",
    categoria: "modulo",
    cobranca: "mensal",
    preco_escritorio_cents: 4225,
    preco_departamento_cents: 4225,
    setup_cents: 120000,
    ativo: true,
    ordem: 50,
  },
  {
    codigo: "legal_analytics",
    nome: "Legal Analytics",
    descricao: "Indicadores para acompanhar a operação e apoiar decisões.",
    categoria: "modulo",
    cobranca: "mensal",
    preco_escritorio_cents: 19990,
    preco_departamento_cents: 19990,
    setup_cents: 0,
    ativo: true,
    ordem: 60,
  },
  {
    codigo: "usuario_legale",
    nome: "Usuário Legale",
    descricao: "Acesso completo à plataforma.",
    categoria: "usuario",
    cobranca: "mensal",
    preco_escritorio_cents: 4790,
    preco_departamento_cents: 4790,
    setup_cents: 0,
    ativo: true,
    ordem: 100,
  },
  {
    codigo: "area_cliente",
    nome: "Área do Cliente",
    descricao: "Acesso destinado ao cliente do escritório.",
    categoria: "usuario",
    cobranca: "mensal",
    preco_escritorio_cents: 4200,
    preco_departamento_cents: 4200,
    setup_cents: 0,
    ativo: true,
    ordem: 110,
  },
  {
    codigo: "usuario_bi",
    nome: "Usuário BI",
    descricao: "Acesso aos painéis de indicadores.",
    categoria: "usuario",
    cobranca: "mensal",
    preco_escritorio_cents: 3990,
    preco_departamento_cents: 3990,
    setup_cents: 0,
    ativo: true,
    ordem: 120,
  },
  {
    codigo: "tv_legale",
    nome: "TV Legale",
    descricao: "Usuário ou dispositivo para exibição de painéis.",
    categoria: "usuario",
    cobranca: "mensal",
    preco_escritorio_cents: 990,
    preco_departamento_cents: 990,
    setup_cents: 0,
    ativo: true,
    ordem: 130,
  },
];
